[tool.black]
target-version = ['py37']
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | env
  | venv
)/
'''

[tool.isort]
profile = 'black'
multi_line_output=3
#import_heading_stdlib='Standard libraries'
#import_heading_thirdparty='Third-party libraries'
#import_heading_firstparty='Local libraries'
