name: test-suite

on: [push, pull_request]

jobs:
  test-suite:
    name: Run test suite via pytest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: [ubuntu-latest, macos-latest]
      python-version: ['3.6', '3.7', '3.8']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Ensure pip, setuptools, and wheel are up to date
        run: python -m pip install --upgrade pip setuptools wheel

      # Install in non-editable mode (no `-e`)
      # Need to install pyface with PyQt5 dependencies
      # pip install pyface[pyqt5]
      # pip install -r requirements.txt
      - name: Install package
        run: |
          pip install .

      # See pytest.ini for configs
      - name: Run tests
        run: pytest ./ --cov-report=xml

      - name: Upload codecov test coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          fail_ci_if_error: true  # fail when codecov runs into errors during upload

      - name: Ensure complete
        run: echo "test-suite complete!"
