name: test-suite

on: [push, pull_request]

jobs:
  test-suite:
    name: Run test suite via pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Qt dependencies for Linux
        run: |
          sudo apt-get update
          sudo apt-get install qt5-default
          sudo apt-get install libxkbcommon-x11-0
          sudo apt-get install libxcb-icccm4
          sudo apt-get install libxcb-image0
          sudo apt-get install libxcb-keysyms1
          sudo apt-get install libxcb-randr0
          sudo apt-get install libxcb-render-util0
          sudo apt-get install libxcb-xinerama0
          sudo apt-get install pulseaudio
          sudo apt-get install libpulse-mainloop-glib0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Ensure pip, setuptools, and wheel are up to date
        run: python -m pip install --upgrade pip setuptools wheel

      # Install in non-editable mode (no `-e`)
      # Need to install pyface with PyQt5 dependencies
      # pip install pyface[pyqt5]
      # pip install -r requirements.txt
      - name: Install package
        run: |
          pip install .

      # See pytest.ini for configs
      - name: Run tests
        run: pytest ./ --cov-report=xml

      - name: Upload codecov test coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          fail_ci_if_error: true  # fail when codecov runs into errors during upload

      - name: Ensure complete
        run: echo "test-suite complete!"
